Fix wibox.layout.stack:raise() returning prematurely and inserting the widget at the end instead of the start
awesomeWM/awesome pull request #3187
Opened 2020-09-26 16:03 UTC by PlayerNameHere

See my issue earlier: #3186.

There seem to be two issues here:

1. The if-statement at the beginning of the function will return prematurely if `self._private.widgets[index]` exists. There seems to be a missing `not` there.
2. The widget is inserted at the end of `self._private.widgets` since no index was specified to `table.insert()`. Index 1 is interpreted as the top of the stack (according to the behaviour that I observed, although the documentation says otherwise). 

For the first, I added the missing `not`. For the second, I pass index `1` to `table.insert()` (`table.insert()` takes an optional index as the second parameter).

2020-09-27 06:00 UTC, Elv13 requested changes
1 little change, but beside :+1:. 

It would be nice to have a regression test in `/spec` (unit test) or `/tests/example/` (test +  documentation example). But if you don't have time, please just say so. It's fine.

2020-09-27 07:35 UTC, psychon commented on lib/wibox/layout/stack.lua
> +    if not index or not self._private.widgets[index] then return end
"less advanced" is for example the person with the second most commits to this repo (https://github.com/awesomeWM/awesome/graphs/contributors) (it's me).
When thinking about it, I guess it makes sense that negation binds stronger than conjunction and disjunction, but when reading such a line of code, my first reaction is "I don't know". (But somehow I do not have that problem when reading C code...)

2020-09-27 07:50 UTC, PlayerNameHere commented on lib/wibox/layout/stack.lua
> +    if not index or not self._private.widgets[index] then return end
I see what you mean! I myself sometimes have trouble depending on my mood and how awake I am. I guess I should make it a habit to always have brackets for clarity. I'll make an amendment soon.

2020-09-27 07:55 UTC, PlayerNameHere commented
I'm not very experienced in testing unfortunately, and I only have 4 days before I get enlisted for mandatory military service (after which I will be in a camp for who knows how long :c). I'll take a look at those folders though and see if I can do anything.

2020-09-27 16:11 UTC, PlayerNameHere commented
I noticed two other small issues in `wibox.layout.stack`:
1. The signals emitted in `set_horizontal_offset()` were wrong &mdash; they should be `widget::layout_changed` & `property::horizontal_offset` instead of `widget::horizontal_offset` & `property::top_only`.
2. There were missing getters for the `horizontal_offset` and `vertical_offset` properties.

I've added two commits to address them. I wasn't sure if I should have created another pull request, but I've done it here for now.

2020-09-28 06:33 UTC, Elv13 approved these changes

2020-09-28 17:53 UTC, actionless approved these changes
thanks!

2020-09-29 06:32 UTC, merged