Improve gears.shape module description.
awesomeWM/awesome pull request #3280
Opened 2021-03-06 16:10 UTC by sclu1034

Fixes #3270.

2021-03-07 10:02 UTC, Aire-One requested changes

2021-03-07 10:02 UTC, Aire-One commented on lib/gears/shape.lua
> +-- parameter followed by a width and height. Individual functions may take additional parameters for their specific implementions.
Can you respect the 80 characters limit?

2021-03-12 06:24 UTC, psychon approved these changes

2021-03-12 06:24 UTC, merged

2021-03-12 06:24 UTC, psychon commented
Thanks!