Remove Vicious as async counterexample
awesomeWM/awesome pull request #3409
Opened 2021-08-12 14:14 UTC by McSinyx

Vicious has stopped using io.popen since October 2019.

2021-08-12 16:00 UTC, actionless approved these changes
lol, finally

2021-08-12 16:00 UTC, actionless commented
still using globals though?

2021-08-12 16:07 UTC, McSinyx commented
I think we localized almost everything in the `io.popen` purge, and we have this in our [contributing guidelines](
https://vicious.readthedocs.io/en/latest/contributing.html#performance-tips) now :smile:

> **Never** use global variables.

2021-08-12 16:12 UTC, actionless commented
> almost everything

ok, please post an update here when you done. thanks for working on improving the code quality.

regarding globals, i meant, if you're still using instead of return values of callback functions?

2021-08-12 16:22 UTC, McSinyx commented
> actually, i've just double-checked on master branch of vicious and i still see 16 usages of io.popen. could you clarify that, please?

I've just check and these are the current usages:

* Those in `contrib` are not supported, they are not officially supported.  We tried working on them but many don't run or we didn't know how to setup.
* `spawn.lua` use popen as a fallback when awesome isn't present.
* `helpers.lua` calls popen exactly once for uname (it's cached) as awesome rc is loaded.

> regarding globals, i meant, if you're still using instead of return values of callback functions?

All officially supported `widgets/` use callback now.

2021-08-12 16:42 UTC, actionless requested changes
nice move instead of fixing or removing them to tell what they're just unsupported, but the thing is what upset users will come here with their complains about why "awesome is slow"

2021-08-13 14:57 UTC, McSinyx commented
To be precise, the [contrib directory](https://drewdevault.com/2020/06/06/Add-a-contrib-directory.html) has never been supported.  If you feel that it's still a risk for users' angry letters, feel free to close this PR.  I only noticed this part of the documentation while browsing the docs for my own use and thought it would be a good idea to communicate the situation of Vicious, after checking Awesome issue tracker for recent related tickets and not finding any.  I do not wish to waste anybody's time discussing back and forth on a few words in the docs that does no harm to neither project if they stay as-is.

2021-08-30 06:59 UTC, Elv13 approved these changes

2021-09-07 20:58 UTC, Elv13 commented
@actionless What do you think about merging this? I feel like they resolved the main reason why we got all of these "AwesomeWM is slow" over the year. Asking for removing this line from the doc seems more than fair.

2021-09-07 21:24 UTC, actionless approved these changes
ok, let's see, if anyone users of that io.popen(curl ...) widget would come back for us later ;)

2021-09-07 21:25 UTC, merged

2021-09-07 21:51 UTC, Elv13 commented
> ok, let's see, if any of users of that io.popen(curl ...) widget would come back for us later ;)

Oh, they will ;). Most configs have a copy pasted version of vicious in their trees. They never get updated and people will still fork these configs. Mentioning vicious in the official doc "forever" just doesn't help them debug all that much.

2021-09-08 06:25 UTC, McSinyx commented
Awesome, thanks!