Replace /usr/bin/which with command -v
awesomeWM/awesome pull request #3439
Opened 2021-09-17 04:11 UTC by madduck

The `which` utility is being phased out since POSIX has mandated
`command -v` for the same task, so let's use that in the awesome-client
script.

Signed-off-by: martin f. krafft <madduck@madduck.net>

2021-09-17 06:14 UTC, actionless commented
have you tried to read your diff yourself before submitting?

2021-09-17 07:10 UTC, sclu1034 requested changes

2021-09-17 07:10 UTC, sclu1034 commented on utils/awesome-client
> +    # rlwrap provides readline functionality for "read", command -v is more enhanced
What @actionless is probably hinting at:
It looks like you just ran a "replace all", which also affected this comment.

2021-09-17 07:36 UTC, madduck commented
Lol, @actionless and @sclu1034, I am sorry to have wasted your time. I had made the commit manually and properly, then made a Git mistake, and then got fed up and did a replace-all, without checking. My bad. Updated now.

2021-09-17 13:35 UTC, actionless approved these changes

2021-09-20 14:55 UTC, Aire-One approved these changes

2021-09-20 17:21 UTC, merged