[doc] Small improvements on the client's icons documentation
awesomeWM/awesome pull request #3509
Opened 2021-11-15 18:20 UTC by Aire-One

This is some small doc improvement to hopefully prevent user from being surprised again.

Close #3508

2021-11-15 20:08 UTC, sclu1034 requested changes

2021-11-15 20:08 UTC, sclu1034 commented on objects/client.c
> + * (by raising this error, the function will return `nil` to the caller).
If a function panics, it cannot return anything, not even `nil`.

2021-11-16 07:40 UTC, sclu1034 approved these changes

2021-11-17 13:54 UTC, actionless approved these changes
thanks!

2021-11-21 09:55 UTC, Elv13 approved these changes

2021-11-21 20:01 UTC, merged