Fix awful.util.geticonpath search order
awesomeWM/awesome pull request #3656
Opened 2022-07-04 10:29 UTC by UbioZur

Fixing the `geticonpath` function to match its documentation of searching first for the size directory.

Issue: https://github.com/awesomeWM/awesome/issues/3646

Given the example:
```lua
awful.util.geticonpath('my-icon', { 'svg', 'png' }, { '/dir1', '/dir2' }, '22')
```

Search pattern before (`xxx` represent the hard-coded sub-folders present in the size folders for a theme):
* search for `/dir1/my-icon.svg`
* search for `/dir1/22x22/xxx/my-icon.svg`
* search for `/dir1/my-icon.png`
* search for `/dir1/22x22/xxx/my-icon.png`
* search for `/dir2/my-icon.svg`
* search for `/dir2/22x22/xxx/my-icon.svg`
* search for `/dir2/my-icon.png`
* search for `/dir2/22x22/xxx/my-icon.png

Search pattern now (`xxx` represent the hard-coded sub-folders present in the size folders for a theme):
* search for `/dir1/22x22/my-icon.svg`
* search for `/dir1/22x22/my-icon.png`
* search for `/dir1/22x22/xxx/my-icon.svg`
* search for `/dir1/22x22/xxx/my-icon.png`
* search for `/dir2/22x22/my-icon.svg`
* search for `/dir2/22x22/my-icon.png`
* search for `/dir2/22x22/xxx/my-icon.svg`
* search for `/dir2/22x22/xxx/my-icon.png`
* search for `/dir1/my-icon.svg`
* search for `/dir1/my-icon.png`
* search for `/dir2/my-icon.svg`
* search for `/dir2/my-icon.png`

## What the fix does not add
* Does not fall back to a different size directory.
* Unsure about the return value if no files are found (I am not good enough in lua to know if it would default to return a nil?)
* Does not find icons inside a sub-directory of `dirs/sizexsize` which is not hard-coded into.

## About Unit Test
I looked around a bit, but I need to look more into it (as I said I have never done any), as there is not much of docs or template for them (All unit test have so many different formatting).
So I need to check/learn, what to install, how to use them and how to create the file. As well as where/how to create dummy icons files (lua function vs touch etc...) to check all the scenario for the unit test. (Feel free to redirect me to any good resources you have).

## Documentation
I fixed the doc from `subdirectories x` to `subdirectories sizexsize`. It's possible more improvement can be made to make it clear on what folders it does search and it does not (but I do not know yet except by example).

Maybe stating what is happening if it couldn't find the icon?! So the user can handle the error.

2022-07-04 12:18 UTC, sclu1034 requested changes
Neither `pairs` nor `gears.table.join` guarantee to preserve the order of numeric indices in their table arguments.
You'll have to use `ipairs` and `gears.table.merge` if you want to get a deterministic order.

2022-07-04 12:18 UTC, sclu1034 commented on lib/awful/util.lua
> +-- @tparam[opt] string size The size. If this is specified, subdirectories `sizexsize`
`sizexsize` is somewhat hard to read and understand if you don't already know the specifics of the directory layout.
Something like this should be easier to understand:

> subdirectories `SIZExSIZE` (e.g. `48x48`)

2022-07-04 12:27 UTC, sclu1034 commented
I guess one general point of discussion (mainly towards maintainers) would be: Do we want proper spec compliance?

- GIF is not officially supported, but XMP is
- the default base `dirs` are in incorrect order, `$HOME/.icons` and proper handling for `$XDG_DATA_DIRS` are missing
- proper theme handling (which has been asked for), including parsing `index.theme` and inheritance
- support for scaling (e.g. `48x48@2`)
- proper handling of subdirectories like `mimetypes` based on theme-defined `Context` (not all icons are meant for applications, even if the name matches)

2022-07-05 01:58 UTC, UbioZur commented on lib/awful/util.lua
> +            local path = string.format("%s%ux%u/", d, size, size)
From a quick manual test on my system, `gfs.file_readable` seems to be able to handle multiple slashes! (good thing to add in a unit test too).

2022-07-05 06:59 UTC, sclu1034 commented on lib/awful/util.lua
> +            local path = string.format("%s%ux%u/", d, size, size)
That does make things easier. But looking through it again, I think we should still collapse them for the final value, to make sure we return a well-formed path:

```lua
return icon:gsub("//+", "/")
```

2022-07-07 01:46 UTC, UbioZur commented on lib/awful/util.lua
> +            local path = string.format("%s%ux%u/", d, size, size)
That's a very good point, thanks.

2022-07-14 15:15 UTC, Aire-One commented
> I guess one general point of discussion (mainly towards maintainers) would be: Do we want proper spec compliance?
> 
>     * GIF is not officially supported, but XMP is
> 
>     * the default base `dirs` are in incorrect order, `$HOME/.icons` and proper handling for `$XDG_DATA_DIRS` are missing
> 
>     * proper theme handling (which has been asked for), including parsing `index.theme` and inheritance
> 
>     * support for scaling (e.g. `48x48@2`)
> 
>     * proper handling of subdirectories like `mimetypes` based on theme-defined `Context` (not all icons are meant for applications, even if the name matches)

Funnily enough, the freedesktop icon theme specification comes with a full example of icon lookup implementation in pseudocode: https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

IMHO:

It's ok to keep the current implementation in `awful.util` somehow more naive. That's a legacy util function we just want to make look more robust. I don't see it evolved that much.

If we want a full compliant implementation, we should rather have some sort of builtin module to handles all the specs and be easily toolable in other modules.

2022-07-14 16:22 UTC, sclu1034 commented on lib/awful/util.lua
> +            local path = string.format("%s%ux%u/", d, size, size)
From a pure logical point of view, your first note invalidates the premise for the second one. As the only difference between the "tested value" and the "modified value" is collapsing consecutive `/` characters, they are, as per the spec, to be considered the same. And therefore we are testing and returning the same value.

Apart from that, we can easily move the sanitization before the check (and to a separate function). I just happened to suggest the low-hanging fruit.
And, if we want to be nice in the context of the spec, we probably should sanitize paths very early. The spec mentions a max length for paths, so while we do need to add one path separator, we might want to make sure not to add multiple, as that would unnecessarily limit the length left to components specified by the user.

2022-07-19 02:18 UTC, UbioZur commented on lib/awful/util.lua
> +            local path = string.format("%s%ux%u/", d, size, size)
We could force sanitized the path before the testing.

```lua
local icon = string.format("%s/%s.%s", d, iconname, e):gsub("//+", "/")
if gfs.file_readable(icon) then
    return icon
```

2023-07-10 07:44 UTC, closed without merging