Some work on the slider widget
awesomeWM/awesome pull request #3695
Opened 2022-09-18 13:47 UTC by thomascft

2022-09-18 17:18 UTC, Aire-One requested changes
Thank you for your work here!

2022-09-18 17:18 UTC, Aire-One commented on lib/wibox/widget/slider.lua
> +    end ]]
Code example doesn't need to be wrapped by block style comments. What's important is to indent them further, so ldoc recognizes them as code-block.

By convention, all ldoc block comments are still single line comments starting with `--`.

Alternatively (and preferably for this kind of feature), we write examples in the `test/examples` directory, then reference the file with a `--@DOC_path_with_underscore_EXAMPLE@` comment line. Running the `ldoc` make target (also ran by the default target) generates images from the examples and inserts them at the corresponding comments' location.

2022-09-18 17:18 UTC, Aire-One commented on lib/wibox/widget/slider.lua
> +        --cr:translate(handle_width*-0.5, handle_width*-0.5)
Please keep your code clean.

2022-09-18 17:18 UTC, Aire-One commented on lib/wibox/widget/slider.lua
> +    handle_icon         = false,
`handle_bgimage` sounds more consistent with other APIs naming

2022-09-19 01:23 UTC, thomascft commented
Sorry, accidental pull request.

2022-09-19 01:23 UTC, closed without merging